/**
 * Transfer Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TransferEntity } from "@provenara/core/shares/models/index.js";
import { sharesSchemas } from "@provenara/core/shares";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "shr";

export function createTransfer(overrides: Partial<TransferEntity> = {}) {
  const raw = {
    id: overrides.id ?? `xfr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    fromInvestorId: overrides.fromInvestorId ?? faker.string.uuid(),
    shareClassId: overrides.shareClassId ?? `shr_${ulid().toLowerCase()}`,
    shares: overrides.shares ?? faker.number.int(),
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    toInvestorId: overrides.toInvestorId ?? faker.string.uuid(),
    ...overrides,
  };

  return sharesSchemas.Transfer.parse(raw);
}

export function transferBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTransfer(overrides));
}
