/**
 * Handlers for Distribution
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SharesDomainModule } from "../dependencies/shares-ddd.dependencies.js";
import type { ListDistributionsInput, RecordDistributionInput } from "@provenara/services/shares";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/share-classes/{shareClassId}/distributions
 * Operation: listDistributions
 */
export async function listDistributions(
  request: FastifyRequest<{ Params: { shareClassId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDistributionsInput = {
    shareClassId: request.params.shareClassId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.distributions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/share-classes/{shareClassId}/distributions
 * Operation: recordDistribution
 */
export async function recordDistribution(
  request: FastifyRequest<{ Params: { shareClassId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordDistributionInput = {
    shareClassId: request.params.shareClassId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.distributions.get.execute(input);
  return reply.code(201).send(result);
}


