/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAlertsDomainModule,
  buildArtworksDomainModule,
  buildAuditsDomainModule,
  buildCounterpartiesDomainModule,
  buildCustodyDomainModule,
  buildIdentityDomainModule,
  buildInsuranceDomainModule,
  buildProvenanceDomainModule,
  buildSharesDomainModule,
  buildTitleDomainModule,
  buildValuationsDomainModule,
} from "../domains/index.js";
import type {
  AlertsDomainModule,
  ArtworksDomainModule,
  AuditsDomainModule,
  CounterpartiesDomainModule,
  CustodyDomainModule,
  IdentityDomainModule,
  InsuranceDomainModule,
  ProvenanceDomainModule,
  SharesDomainModule,
  TitleDomainModule,
  ValuationsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private alertsModule: AlertsDomainModule | null = null;
  private artworksModule: ArtworksDomainModule | null = null;
  private auditsModule: AuditsDomainModule | null = null;
  private counterpartiesModule: CounterpartiesDomainModule | null = null;
  private custodyModule: CustodyDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private insuranceModule: InsuranceDomainModule | null = null;
  private provenanceModule: ProvenanceDomainModule | null = null;
  private sharesModule: SharesDomainModule | null = null;
  private titleModule: TitleDomainModule | null = null;
  private valuationsModule: ValuationsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get alerts domain module
   */
  getAlertsDependencies(): AlertsDomainModule {
    if (!this.alertsModule) {
      this.alertsModule = buildAlertsDomainModule(this.dynamoClient);
    }
    return this.alertsModule;
  }

  /**
   * Get artworks domain module
   */
  getArtworksDependencies(): ArtworksDomainModule {
    if (!this.artworksModule) {
      this.artworksModule = buildArtworksDomainModule(this.dynamoClient);
    }
    return this.artworksModule;
  }

  /**
   * Get audits domain module
   */
  getAuditsDependencies(): AuditsDomainModule {
    if (!this.auditsModule) {
      this.auditsModule = buildAuditsDomainModule(this.dynamoClient);
    }
    return this.auditsModule;
  }

  /**
   * Get counterparties domain module
   */
  getCounterpartiesDependencies(): CounterpartiesDomainModule {
    if (!this.counterpartiesModule) {
      this.counterpartiesModule = buildCounterpartiesDomainModule(this.dynamoClient);
    }
    return this.counterpartiesModule;
  }

  /**
   * Get custody domain module
   */
  getCustodyDependencies(): CustodyDomainModule {
    if (!this.custodyModule) {
      this.custodyModule = buildCustodyDomainModule(this.dynamoClient);
    }
    return this.custodyModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get insurance domain module
   */
  getInsuranceDependencies(): InsuranceDomainModule {
    if (!this.insuranceModule) {
      this.insuranceModule = buildInsuranceDomainModule(this.dynamoClient);
    }
    return this.insuranceModule;
  }

  /**
   * Get provenance domain module
   */
  getProvenanceDependencies(): ProvenanceDomainModule {
    if (!this.provenanceModule) {
      this.provenanceModule = buildProvenanceDomainModule(this.dynamoClient);
    }
    return this.provenanceModule;
  }

  /**
   * Get shares domain module
   */
  getSharesDependencies(): SharesDomainModule {
    if (!this.sharesModule) {
      this.sharesModule = buildSharesDomainModule(this.dynamoClient);
    }
    return this.sharesModule;
  }

  /**
   * Get title domain module
   */
  getTitleDependencies(): TitleDomainModule {
    if (!this.titleModule) {
      this.titleModule = buildTitleDomainModule(this.dynamoClient);
    }
    return this.titleModule;
  }

  /**
   * Get valuations domain module
   */
  getValuationsDependencies(): ValuationsDomainModule {
    if (!this.valuationsModule) {
      this.valuationsModule = buildValuationsDomainModule(this.dynamoClient);
    }
    return this.valuationsModule;
  }

  clearAlertsDependencies(): void { this.alertsModule = null; }
  clearArtworksDependencies(): void { this.artworksModule = null; }
  clearAuditsDependencies(): void { this.auditsModule = null; }
  clearCounterpartiesDependencies(): void { this.counterpartiesModule = null; }
  clearCustodyDependencies(): void { this.custodyModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearInsuranceDependencies(): void { this.insuranceModule = null; }
  clearProvenanceDependencies(): void { this.provenanceModule = null; }
  clearSharesDependencies(): void { this.sharesModule = null; }
  clearTitleDependencies(): void { this.titleModule = null; }
  clearValuationsDependencies(): void { this.valuationsModule = null; }

  getAlertsDependenciesForRequest(): AlertsDomainModule {
    return this.getAlertsDependencies();
  }

  getArtworksDependenciesForRequest(): ArtworksDomainModule {
    return this.getArtworksDependencies();
  }

  getAuditsDependenciesForRequest(): AuditsDomainModule {
    return this.getAuditsDependencies();
  }

  getCounterpartiesDependenciesForRequest(): CounterpartiesDomainModule {
    return this.getCounterpartiesDependencies();
  }

  getCustodyDependenciesForRequest(): CustodyDomainModule {
    return this.getCustodyDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getInsuranceDependenciesForRequest(): InsuranceDomainModule {
    return this.getInsuranceDependencies();
  }

  getProvenanceDependenciesForRequest(): ProvenanceDomainModule {
    return this.getProvenanceDependencies();
  }

  getSharesDependenciesForRequest(): SharesDomainModule {
    return this.getSharesDependencies();
  }

  getTitleDependenciesForRequest(): TitleDomainModule {
    return this.getTitleDependencies();
  }

  getValuationsDependenciesForRequest(): ValuationsDomainModule {
    return this.getValuationsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.alertsModule = null;
    this.artworksModule = null;
    this.auditsModule = null;
    this.counterpartiesModule = null;
    this.custodyModule = null;
    this.identityModule = null;
    this.insuranceModule = null;
    this.provenanceModule = null;
    this.sharesModule = null;
    this.titleModule = null;
    this.valuationsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
