/**
 * Document DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Document DTOs
 *
 * DDD: Application DTOs for Document use cases.
 */

import type { AttachDocumentArtefactParams, AttachDocumentArtefactRequestInput, ListDocumentArtefactsParams } from "@provenara/core/provenance/types";

export type ListDocumentArtefactsInput = ListDocumentArtefactsParams;

export type AttachDocumentArtefactInput = AttachDocumentArtefactParams & AttachDocumentArtefactRequestInput;

export type ListDocumentArtefactsOutput = {};

export type AttachDocumentArtefactOutput = {};
