/**
 * Provenance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Provenance DTOs
 *
 * DDD: Application DTOs for Provenance use cases.
 */

import type { AppendProvenanceParams, AppendProvenanceRequestInput, ListProvenanceParams } from "@provenara/core/provenance/types";

export type ListProvenanceInput = ListProvenanceParams;

export type AppendProvenanceInput = AppendProvenanceParams & AppendProvenanceRequestInput;

export type ListProvenanceOutput = {};

export type AppendProvenanceOutput = {};
