/**
 * InsuranceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InsuranceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InsuranceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InsuranceRepository,
} from "@provenara/services/insurance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InsuranceRepositoryDdb } from "./insurance-repository.ddb.js";

/**
 * InsuranceRepositoryAdapter
 *
 * Implements InsuranceRepository port for infrastructure layer.
 */
export class InsuranceRepositoryAdapter implements InsuranceRepository {
  private readonly ddb: InsuranceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InsuranceRepositoryDdb(this.dynamoClient);
  }

  async listInsurancePolicies(input: Parameters<InsuranceRepository['listInsurancePolicies']>[0]): Promise<Awaited<ReturnType<InsuranceRepository['listInsurancePolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listInsurancePolicies(input);
  }

  async bindInsurancePolicy(input: Parameters<InsuranceRepository['bindInsurancePolicy']>[0]): Promise<Awaited<ReturnType<InsuranceRepository['bindInsurancePolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.bindInsurancePolicy(input);
  }
}
