/**
 * Routes for Screen
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { screenCounterparty } from "../handlers/screen.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function screenRoutes(fastify: FastifyInstance) {
  // POST /v1/counterparties/{counterpartyId}/screen (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/counterparties/:counterpartyId/screen",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { counterpartyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCounterpartiesDependenciesForRequest();
        await screenCounterparty(request, reply, deps);
      });
    }
  );


}
