/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Alerts Domain Use Cases
 * 
 * List of all use case names for the alerts domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ALERTS_USE_CASES = [
  "executeAssignRiskAlert",
  "executeGetRiskAlert",
  "executeListRiskAlerts",
  "executeResolveRiskAlert"
] as const;
