/**
 * ListEncumbrance DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEncumbrancesParams } from "@provenara/core/title";

export function createListEncumbranceRequest(overrides: Partial<ListEncumbrancesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
