/**
 * ExpireRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpireRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExpireRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExpireRepository,
} from "@provenara/services/valuations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExpireRepositoryDdb } from "./expire-repository.ddb.js";

/**
 * ExpireRepositoryAdapter
 *
 * Implements ExpireRepository port for infrastructure layer.
 */
export class ExpireRepositoryAdapter implements ExpireRepository {
  private readonly ddb: ExpireRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExpireRepositoryDdb(this.dynamoClient);
  }

  async expireValuation(input: Parameters<ExpireRepository['expireValuation']>[0]): Promise<Awaited<ReturnType<ExpireRepository['expireValuation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.expireValuation(input);
  }
}
