/**
 * ValuationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValuationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ValuationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ValuationRepository,
} from "@provenara/services/valuations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ValuationRepositoryDdb } from "./valuation-repository.ddb.js";

/**
 * ValuationRepositoryAdapter
 *
 * Implements ValuationRepository port for infrastructure layer.
 */
export class ValuationRepositoryAdapter implements ValuationRepository {
  private readonly ddb: ValuationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ValuationRepositoryDdb(this.dynamoClient);
  }

  async listValuations(input: Parameters<ValuationRepository['listValuations']>[0]): Promise<Awaited<ReturnType<ValuationRepository['listValuations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listValuations(input);
  }

  async addValuation(input: Parameters<ValuationRepository['addValuation']>[0]): Promise<Awaited<ReturnType<ValuationRepository['addValuation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.addValuation(input);
  }
}
