/**
 * ListArtworks handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listArtworks } from "@provenara/api-server/domains/artworks/handlers";
import type { ArtworksDDDDependencies } from "@provenara/api-server/domains/artworks";
import { createArtwork as createArtworkEntity } from "@provenara/factories/artworks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { ARTWORKS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListArtworks", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ArtworksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ArtworksDDDDependencies>(
      ARTWORKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createArtworkEntity({ orgId }),
      createArtworkEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListArtworks, "execute").mockResolvedValue(useCaseResult);

    await listArtworks(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListArtworks.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
