/**
 * Document Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DocumentEntity } from "@provenara/core/provenance/models/index.js";
import { provenanceSchemas } from "@provenara/core/provenance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prv";

export function createDocument(overrides: Partial<DocumentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `doc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artworkId: overrides.artworkId ?? faker.string.uuid(),
    contentHash: overrides.contentHash ?? faker.lorem.word(),
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return provenanceSchemas.DocumentArtefact.parse(raw);
}

export function documentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDocument(overrides));
}
