/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Counterparties Domain Use Cases
 * 
 * List of all use case names for the counterparties domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COUNTERPARTIES_USE_CASES = [
  "executeCreateCounterparty",
  "executeGetCounterparty",
  "executeListCounterparties",
  "executeOverrideScreenResult",
  "executeScreenCounterparty"
] as const;
