/**
 * Distribution Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DistributionEntity } from "@provenara/core/shares/models/index.js";
import { sharesSchemas } from "@provenara/core/shares";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "shr";

export function createDistribution(overrides: Partial<DistributionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dst_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? faker.number.int(),
    currency: overrides.currency ?? faker.lorem.word(),
    shareClassId: overrides.shareClassId ?? `shr_${ulid().toLowerCase()}`,
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return sharesSchemas.Distribution.parse(raw);
}

export function distributionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDistribution(overrides));
}
