/**
 * Repository interface for Subscription
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SubscriptionEntity
} from "../models/subscription.entity.js";
import type {
  ListInvestorPositionsParams,
  InvestorPosition
} from "../types/index.js";
/**
 * SubscriptionRepository Interface
 */
export interface SubscriptionRepository extends CreateReadRepository<SubscriptionEntity, InvestorPosition, string, ListInvestorPositionsParams> {

}
