/**
 * Artwork DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Artwork DTOs
 *
 * DDD: Application DTOs for Artwork use cases.
 */

import type { CreateArtworkRequestInput, GetArtworkParams, ListArtworksParams } from "@provenara/core/artworks/types";

export type ListArtworksInput = ListArtworksParams;

export type CreateArtworkInput = CreateArtworkRequestInput;

export type GetArtworkInput = GetArtworkParams;

export type ListArtworksOutput = {};

export type CreateArtworkOutput = {};

export type GetArtworkOutput = {};
