/**
 * TrustFile DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustFile DTOs
 *
 * DDD: Application DTOs for TrustFile use cases.
 */

import type { GetTrustFileParams } from "@provenara/core/artworks/types";

export type GetTrustFileInput = GetTrustFileParams;

export type GetTrustFileOutput = {};
