/**
 * Handlers for Encumbrance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TitleDomainModule } from "../dependencies/title-ddd.dependencies.js";
import type { ListEncumbrancesInput, RecordEncumbranceInput } from "@provenara/services/title";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/artworks/{artworkId}/encumbrances
 * Operation: listEncumbrances
 */
export async function listEncumbrances(
  request: FastifyRequest<{ Params: { artworkId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TitleDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEncumbrancesInput = {
    artworkId: request.params.artworkId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.encumbrances.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/artworks/{artworkId}/encumbrances
 * Operation: recordEncumbrance
 */
export async function recordEncumbrance(
  request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TitleDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordEncumbranceInput = {
    artworkId: request.params.artworkId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.encumbrances.get.execute(input);
  return reply.code(201).send(result);
}


