/**
 * Handlers for Release
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TitleDomainModule } from "../dependencies/title-ddd.dependencies.js";
import type { ReleaseEncumbranceInput } from "@provenara/services/title";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/artworks/{artworkId}/encumbrances/{encumbranceId}/release
 * Operation: releaseEncumbrance
 */
export async function releaseEncumbrance(
  request: FastifyRequest<{ Params: { artworkId: string, encumbranceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TitleDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReleaseEncumbranceInput = {
    artworkId: request.params.artworkId,
    encumbranceId: request.params.encumbranceId,
  };
  const result = await deps.useCases.releases.get.execute(input);
  return reply.code(200).send(result);
}


