/**
 * DistributionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DistributionRepository Port
 *
 * DDD: Application port for distributionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListDistributionsInput, ListDistributionsOutput, RecordDistributionInput, RecordDistributionOutput } from "../dto/distribution.dto";
export interface DistributionRepository {
  listDistributions(input: ListDistributionsInput): Promise<ListDistributionsOutput>;
  recordDistribution(input: RecordDistributionInput): Promise<RecordDistributionOutput>;
}

export type { ListDistributionsInput, ListDistributionsOutput, RecordDistributionInput, RecordDistributionOutput } from "../dto/distribution.dto";
