/**
 * ShareClassRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShareClassRepository Port
 *
 * DDD: Application port for shareclassrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateShareClassInput, CreateShareClassOutput, GetShareClassInput, GetShareClassOutput, ListShareClassesInput, ListShareClassesOutput } from "../dto/share-class.dto";
export interface ShareClassRepository {
  listShareClasses(input: ListShareClassesInput): Promise<ListShareClassesOutput>;
  createShareClass(input: CreateShareClassInput): Promise<CreateShareClassOutput>;
  getShareClass(input: GetShareClassInput): Promise<GetShareClassOutput>;
}

export type { CreateShareClassInput, CreateShareClassOutput, GetShareClassInput, GetShareClassOutput, ListShareClassesInput, ListShareClassesOutput } from "../dto/share-class.dto";
