/**
 * SubscriptionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubscriptionRepository Port
 *
 * DDD: Application port for subscriptionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListInvestorPositionsInput, ListInvestorPositionsOutput, SubscribeSharesInput, SubscribeSharesOutput } from "../dto/subscription.dto";
export interface SubscriptionRepository {
  listInvestorPositions(input: ListInvestorPositionsInput): Promise<ListInvestorPositionsOutput>;
  subscribeShares(input: SubscribeSharesInput): Promise<SubscribeSharesOutput>;
}

export type { ListInvestorPositionsInput, ListInvestorPositionsOutput, SubscribeSharesInput, SubscribeSharesOutput } from "../dto/subscription.dto";
