/**
 * Insurance Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { InsuranceEntity } from "@provenara/core/insurance/models/index.js";
import { insuranceSchemas } from "@provenara/core/insurance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ins";

export function createInsurance(overrides: Partial<InsuranceEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ins_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artworkId: overrides.artworkId ?? faker.string.uuid(),
    status: overrides.status ?? "bound",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return insuranceSchemas.InsurancePolicy.parse(raw);
}

export function insuranceBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createInsurance(overrides));
}
