/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Custody Domain Use Cases
 * 
 * List of all use case names for the custody domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CUSTODY_USE_CASES = [
  "executeAttestCustody",
  "executeClearCustodyMismatch",
  "executeFlagCustodyMismatch",
  "executeListCustodyEvents"
] as const;
