/**
 * ShareClass DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShareClass DTOs
 *
 * DDD: Application DTOs for ShareClass use cases.
 */

import type { CreateShareClassRequestInput, GetShareClassParams, ListShareClassesParams } from "@provenara/core/shares/types";

export type ListShareClassesInput = ListShareClassesParams;

export type CreateShareClassInput = CreateShareClassRequestInput;

export type GetShareClassInput = GetShareClassParams;

export type ListShareClassesOutput = {};

export type CreateShareClassOutput = {};

export type GetShareClassOutput = {};
