/**
 * Subscription DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Subscription DTOs
 *
 * DDD: Application DTOs for Subscription use cases.
 */

import type { ListInvestorPositionsParams, SubscribeSharesParams, SubscribeSharesRequestInput } from "@provenara/core/shares/types";

export type ListInvestorPositionsInput = ListInvestorPositionsParams;

export type SubscribeSharesInput = SubscribeSharesParams & SubscribeSharesRequestInput;

export type ListInvestorPositionsOutput = {};

export type SubscribeSharesOutput = {};
