/**
 * Transfer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Transfer DTOs
 *
 * DDD: Application DTOs for Transfer use cases.
 */

import type { TransferSharesParams, TransferSharesRequestInput } from "@provenara/core/shares/types";

export type TransferSharesInput = TransferSharesParams & TransferSharesRequestInput;

export type TransferSharesOutput = {};
