/**
 * ExecuteListProvenance - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListProvenance Use Case
 *
 * DDD: Application use case for list Provenance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListProvenanceInput, ListProvenanceOutput } from "../dto/provenance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ProvenanceRepository } from "../ports";

export class ExecuteListProvenance {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly provenance: ProvenanceRepository
  ) {}

  async execute(input: ListProvenanceInput): Promise<ListProvenanceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prvId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.provenance.listProvenance({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListProvenanceOutput;
  }
}
