/**
 * ExecuteAttachDocumentArtefact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttachDocumentArtefact Use Case
 *
 * DDD: Application use case for get Document.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttachDocumentArtefactInput, AttachDocumentArtefactOutput } from "../dto/document.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { DocumentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttachDocumentArtefact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly document: DocumentRepository
  ) {}

  async execute(input: AttachDocumentArtefactInput): Promise<AttachDocumentArtefactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prvId();

    // All field names extracted from OpenAPI spec: contentHash, label, linkedEventId, uri
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artworkId) {
      throw new ValidationError("artworkId is required");
    }
    const artworkId = (input as any).artworkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.document.attachDocumentArtefact({ artworkId: artworkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artworkId}`);
    }

    return entity as AttachDocumentArtefactOutput;
  }
}
