/**
 * ExecuteListDocumentArtefacts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDocumentArtefacts Use Case
 *
 * DDD: Application use case for list Document.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDocumentArtefactsInput, ListDocumentArtefactsOutput } from "../dto/document.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { DocumentRepository } from "../ports";

export class ExecuteListDocumentArtefacts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly document: DocumentRepository
  ) {}

  async execute(input: ListDocumentArtefactsInput): Promise<ListDocumentArtefactsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prvId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.document.listDocumentArtefacts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDocumentArtefactsOutput;
  }
}
