/**
 * Release Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/title.openapi.types.js";
import { schemas } from "../schemas/title.schemas.js";

/**
 * Entity: ReleaseEntity
 * Description: Represents the Release domain model.
 * Source: schemas.Encumbrance
 * Type: Persisted Entity (x-dynamodb)
 */
export const ReleaseEntitySchema = schemas.Encumbrance;
export type ReleaseEntity = components["schemas"]["Encumbrance"];
