/**
 * Title Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/title.openapi.types.js";
import { schemas } from "../schemas/title.schemas.js";

/**
 * Entity: TitleEntity
 * Description: Represents the Title domain model.
 * Source: schemas.TitleStatus
 * Type: Persisted Entity (x-dynamodb)
 */
export const TitleEntitySchema = schemas.TitleStatus;
export type TitleEntity = components["schemas"]["TitleStatus"];
