/**
 * AttachDocumentArtefact handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { attachDocumentArtefact } from "@provenara/api-server/domains/provenance/handlers";
import type { ProvenanceDDDDependencies } from "@provenara/api-server/domains/provenance";
import { createDocument as createDocumentEntity } from "@provenara/factories/provenance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { PROVENANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("AttachDocumentArtefact", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProvenanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProvenanceDDDDependencies>(
      PROVENANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDocumentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAttachDocumentArtefact, "execute").mockResolvedValue(useCaseResult);

    await attachDocumentArtefact(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAttachDocumentArtefact.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
