/**
 * Document Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/provenance.openapi.types.js";
import { schemas } from "../schemas/provenance.schemas.js";

/**
 * Entity: DocumentEntity
 * Description: Represents the Document domain model.
 * Source: schemas.DocumentArtefact
 * Type: Persisted Entity (x-dynamodb)
 */
export const DocumentEntitySchema = schemas.DocumentArtefact;
export type DocumentEntity = components["schemas"]["DocumentArtefact"];
