/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@provenara/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "alerts", "artworks", "audits", "counterparties", "custody", "identity", "insurance", "provenance", "shares", "title", "valuations"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      alerts: [{ method: "GET", path: "/v1/alerts" }, { method: "GET", path: "/v1/alerts/:alertId" }, { method: "POST", path: "/v1/alerts/:alertId/assign" }, { method: "POST", path: "/v1/alerts/:alertId/resolve" }],
      artworks: [{ method: "GET", path: "/v1/artworks" }, { method: "POST", path: "/v1/artworks" }, { method: "GET", path: "/v1/artworks/:artworkId" }, { method: "GET", path: "/v1/artworks/:artworkId/trust-file" }],
      audits: [{ method: "POST", path: "/v1/audits/exports" }, { method: "GET", path: "/v1/audits/exports/:exportId" }, { method: "GET", path: "/v1/artworks/:artworkId/anchors" }, { method: "POST", path: "/v1/artworks/:artworkId/anchors" }],
      counterparties: [{ method: "GET", path: "/v1/counterparties" }, { method: "POST", path: "/v1/counterparties" }, { method: "GET", path: "/v1/counterparties/:counterpartyId" }, { method: "POST", path: "/v1/counterparties/:counterpartyId/screen" }, { method: "POST", path: "/v1/counterparties/:counterpartyId/screen/override" }],
      custody: [{ method: "GET", path: "/v1/artworks/:artworkId/custody" }, { method: "POST", path: "/v1/artworks/:artworkId/custody" }, { method: "POST", path: "/v1/artworks/:artworkId/custody/mismatch" }, { method: "DELETE", path: "/v1/artworks/:artworkId/custody/mismatch" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      insurance: [{ method: "GET", path: "/v1/artworks/:artworkId/insurance" }, { method: "POST", path: "/v1/artworks/:artworkId/insurance" }, { method: "POST", path: "/v1/artworks/:artworkId/insurance/:policyId/lapse" }],
      provenance: [{ method: "GET", path: "/v1/artworks/:artworkId/provenance" }, { method: "POST", path: "/v1/artworks/:artworkId/provenance" }, { method: "GET", path: "/v1/artworks/:artworkId/documents" }, { method: "POST", path: "/v1/artworks/:artworkId/documents" }],
      shares: [{ method: "GET", path: "/v1/share-classes" }, { method: "POST", path: "/v1/share-classes" }, { method: "GET", path: "/v1/share-classes/:shareClassId" }, { method: "GET", path: "/v1/share-classes/:shareClassId/subscriptions" }, { method: "POST", path: "/v1/share-classes/:shareClassId/subscriptions" }, { method: "POST", path: "/v1/share-classes/:shareClassId/transfers" }, { method: "POST", path: "/v1/share-classes/:shareClassId/freeze" }, { method: "GET", path: "/v1/share-classes/:shareClassId/distributions" }, { method: "POST", path: "/v1/share-classes/:shareClassId/distributions" }],
      title: [{ method: "GET", path: "/v1/artworks/:artworkId/title" }, { method: "PUT", path: "/v1/artworks/:artworkId/title" }, { method: "GET", path: "/v1/artworks/:artworkId/encumbrances" }, { method: "POST", path: "/v1/artworks/:artworkId/encumbrances" }, { method: "POST", path: "/v1/artworks/:artworkId/encumbrances/:encumbranceId/release" }],
      valuations: [{ method: "GET", path: "/v1/artworks/:artworkId/valuations" }, { method: "POST", path: "/v1/artworks/:artworkId/valuations" }, { method: "POST", path: "/v1/artworks/:artworkId/valuations/:valuationId/expire" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
