/**
 * TrustFile Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/artworks.openapi.types.js";
import { schemas } from "../schemas/artworks.schemas.js";

/**
 * Entity: TrustFileEntity
 * Description: Represents the TrustFile domain model.
 * Source: schemas.TrustFile
 * Type: Persisted Entity (x-dynamodb)
 */
export const TrustFileEntitySchema = schemas.TrustFile;
export type TrustFileEntity = components["schemas"]["TrustFile"];
