/**
 * CustodyRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CustodyRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing Custody repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { CustodyRepository } from "@provenara/services/custody";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * CustodyRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: CUSTODY_EVENT
 * Entity Token: CUSTODY_EVENT
 * SK Prefix: CUSTODY_EVENT
 */
export class CustodyRepositoryDdb implements CustodyRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "CUSTODY_EVENT";
  private readonly ENTITY_TOKEN = "CUSTODY_EVENT";
  private readonly SK_PREFIX = "CUSTODY_EVENT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "CUSTODY";
  private readonly ENTITY_TYPE_PK = "CUSTODY_EVENTS";
  private generateCorrelationId(): string {
    const domainPrefix = "cus";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async listCustodyEvents(input: Parameters<CustodyRepository['listCustodyEvents']>[0]): Promise<Awaited<ReturnType<CustodyRepository['listCustodyEvents']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const gsi2PK = `ORG#${inputExt.orgId}#${this.ENTITY_TYPE_PK}`;
    const rawLimit = inputExt?.limit;
    const parsedLimit = rawLimit == null || rawLimit === ""
      ? 50
      : (typeof rawLimit === "string" ? parseInt(rawLimit as string, 10) : Number(rawLimit));
    const limit = Number.isFinite(parsedLimit) && parsedLimit > 0 ? parsedLimit : 50;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      IndexName: "GSI2",
      KeyConditionExpression: "#gsi2pk = :pk",
      ExpressionAttributeNames: { "#gsi2pk": "GSI2-PK" },

      ExpressionAttributeValues: {
        ":pk": gsi2PK,
      },
      Limit: limit,
      ScanIndexForward: false,
      ...((() => {
        const c = inputExt?.cursor;
        if (!c || (typeof c === "string" && !c.trim())) return {};
        try {
          return {
            ExclusiveStartKey: typeof c === "string"
              ? JSON.parse(Buffer.from(c, "base64").toString())
              : c,
          };
        } catch {
          return {};
        }
      })()),
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    return {
      data: { items: items } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
        pagination: {
          nextCursor: result.LastEvaluatedKey ? Buffer.from(JSON.stringify(result.LastEvaluatedKey)).toString("base64") : null,
          prevCursor: null,
          limit: inputExt?.limit || 50,
        },
      } as unknown as any,
    };
  }

  async attestCustody(input: Parameters<CustodyRepository['attestCustody']>[0]): Promise<Awaited<ReturnType<CustodyRepository['attestCustody']>>> {
    const inputExt = input as Record<string, unknown>;

    const idVal = inputExt.artworkId;
    if (!idVal || !inputExt.orgId) throw new Error("Missing required parameter: ruleId/id or orgId");
    const pk = this.buildPK(inputExt.orgId as string, idVal as string);
    const getResult = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": `${this.ENTITY_TOKEN}#${idVal}#` },
      Limit: 1,
    });
    const item = getResult.Items?.[0];
    if (!item) throw new Error(`${this.ENTITY_TYPE} with id ${idVal} not found`);
    return {
      data: { success: true } as unknown as any,
      meta: { correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(), timestamp: new Date().toISOString() } as unknown as any,
    };
  }
}
