/**
 * CustodyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CustodyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CustodyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CustodyRepository,
} from "@provenara/services/custody";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CustodyRepositoryDdb } from "./custody-repository.ddb.js";

/**
 * CustodyRepositoryAdapter
 *
 * Implements CustodyRepository port for infrastructure layer.
 */
export class CustodyRepositoryAdapter implements CustodyRepository {
  private readonly ddb: CustodyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CustodyRepositoryDdb(this.dynamoClient);
  }

  async listCustodyEvents(input: Parameters<CustodyRepository['listCustodyEvents']>[0]): Promise<Awaited<ReturnType<CustodyRepository['listCustodyEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCustodyEvents(input);
  }

  async attestCustody(input: Parameters<CustodyRepository['attestCustody']>[0]): Promise<Awaited<ReturnType<CustodyRepository['attestCustody']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attestCustody(input);
  }
}
