/**
 * Handlers for Provenance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProvenanceDomainModule } from "../dependencies/provenance-ddd.dependencies.js";
import type { AppendProvenanceInput, ListProvenanceInput } from "@provenara/services/provenance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/artworks/{artworkId}/provenance
 * Operation: listProvenance
 */
export async function listProvenance(
  request: FastifyRequest<{ Params: { artworkId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListProvenanceInput = {
    artworkId: request.params.artworkId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.provenances.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/artworks/{artworkId}/provenance
 * Operation: appendProvenance
 */
export async function appendProvenance(
  request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AppendProvenanceInput = {
    artworkId: request.params.artworkId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.provenances.get.execute(input);
  return reply.code(201).send(result);
}


