/**
 * ListInvestorPositions handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listInvestorPositions } from "@provenara/api-server/domains/shares/handlers";
import type { SharesDDDDependencies } from "@provenara/api-server/domains/shares";
import { createSubscription as createSubscriptionEntity } from "@provenara/factories/shares";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { SHARES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListInvestorPositions", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SharesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SharesDDDDependencies>(
      SHARES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSubscriptionEntity({ orgId }),
      createSubscriptionEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListInvestorPositions, "execute").mockResolvedValue(useCaseResult);

    await listInvestorPositions(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListInvestorPositions.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
