/**
 * ListCustody DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCustodyEventsParams } from "@provenara/core/custody";

export function createListCustodyRequest(overrides: Partial<ListCustodyEventsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
