/**
 * ReleaseEncumbrance handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { releaseEncumbrance } from "@provenara/api-server/domains/title/handlers";
import type { TitleDDDDependencies } from "@provenara/api-server/domains/title";
import { createRelease as createReleaseEntity } from "@provenara/factories/title";
import { createCreateReleaseRequest } from "@provenara/factories/title";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { TITLE_USE_CASES } from "../__factories__/use-cases.js";

describe("ReleaseEncumbrance", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TitleDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TitleDDDDependencies>(
      TITLE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateReleaseRequest();
    const entity = createReleaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeReleaseEncumbrance, "execute").mockResolvedValue(useCaseResult);

    await releaseEncumbrance(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeReleaseEncumbrance.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
