/**
 * Custody DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Custody Domain Module - Composition root
 *
 * DDD: Composition root for custody domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CustodyRepositoryAdapter,
  MismatchRepositoryAdapter,
} from "@provenara/adapters/custody";
import { getIdGeneratorService } from "@provenara/adapters";
import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttestCustody,
  ExecuteClearCustodyMismatch,
  ExecuteFlagCustodyMismatch,
  ExecuteListCustodyEvents,
} from "@provenara/services/custody/usecases";
// Ports (interfaces)
import type {
  CustodyRepository,
  MismatchRepository,
} from "@provenara/services/custody/ports";

export interface CustodyDomainModule {
  repos: {
    custodies: CustodyRepository;
    mismatches: MismatchRepository;
  };
  useCases: {
    custodies: {
      get: ExecuteAttestCustody;
      list: ExecuteListCustodyEvents;
    };
    mismatches: {
      get: ExecuteClearCustodyMismatch;
    };
  };
}

export function buildCustodyDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CustodyDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      custodies?: CustodyRepository;
      mismatches?: MismatchRepository;
    } = {};

    obj.custodies = new CustodyRepositoryAdapter(dynamoClient);
    obj.mismatches = new MismatchRepositoryAdapter(dynamoClient);
    return {
      custodies: obj.custodies!,
      mismatches: obj.mismatches!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    custodies: {
      get: new ExecuteAttestCustody(executionContext, idGenerator, repos.custodies),
      list: new ExecuteListCustodyEvents(executionContext, idGenerator, repos.custodies),
    },
    mismatches: {
      get: new ExecuteClearCustodyMismatch(executionContext, idGenerator, repos.mismatches),
    },
  };
  return { repos, useCases: useCases as CustodyDomainModule["useCases"] };
}
