/**
 * Mismatch Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/custody.openapi.types.js";
import { schemas } from "../schemas/custody.schemas.js";

/**
 * Entity: MismatchEntity
 * Description: Represents the Mismatch domain model.
 * Source: schemas.CustodyEvent
 * Type: Persisted Entity (x-dynamodb)
 */
export const MismatchEntitySchema = schemas.CustodyEvent;
export type MismatchEntity = components["schemas"]["CustodyEvent"];
