/**
 * Routes for Encumbrance
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listEncumbrances, recordEncumbrance } from "../handlers/encumbrance.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function encumbranceRoutes(fastify: FastifyInstance) {
  // GET /v1/artworks/{artworkId}/encumbrances (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/artworks/:artworkId/encumbrances",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTitleDependenciesForRequest();
        await listEncumbrances(request, reply, deps);
      });
    }
  );


  // POST /v1/artworks/{artworkId}/encumbrances (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/artworks/:artworkId/encumbrances",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTitleDependenciesForRequest();
        await recordEncumbrance(request, reply, deps);
      });
    }
  );


}
