/**
 * Encumbrance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Encumbrance DTOs
 *
 * DDD: Application DTOs for Encumbrance use cases.
 */

import type { ListEncumbrancesParams, RecordEncumbranceParams, RecordEncumbranceRequestInput } from "@provenara/core/title/types";

export type ListEncumbrancesInput = ListEncumbrancesParams;

export type RecordEncumbranceInput = RecordEncumbranceParams & RecordEncumbranceRequestInput;

export type ListEncumbrancesOutput = {};

export type RecordEncumbranceOutput = {};
