/**
 * ListInsurancePolicies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listInsurancePolicies } from "@provenara/api-server/domains/insurance/handlers";
import type { InsuranceDDDDependencies } from "@provenara/api-server/domains/insurance";
import { createInsurance as createInsuranceEntity } from "@provenara/factories/insurance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { INSURANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListInsurancePolicies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InsuranceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InsuranceDDDDependencies>(
      INSURANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createInsuranceEntity({ orgId }),
      createInsuranceEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListInsurancePolicies, "execute").mockResolvedValue(useCaseResult);

    await listInsurancePolicies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListInsurancePolicies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
