/**
 * TitleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TitleRepository Port
 *
 * DDD: Application port for titlerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTitleStatusInput, GetTitleStatusOutput, UpsertTitleStatusInput, UpsertTitleStatusOutput } from "../dto/title.dto";
export interface TitleRepository {
  getTitleStatus(input: GetTitleStatusInput): Promise<GetTitleStatusOutput>;
  upsertTitleStatus(input: UpsertTitleStatusInput): Promise<UpsertTitleStatusOutput>;
}

export type { GetTitleStatusInput, GetTitleStatusOutput, UpsertTitleStatusInput, UpsertTitleStatusOutput } from "../dto/title.dto";
