/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Provenance Domain Use Cases
 * 
 * List of all use case names for the provenance domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PROVENANCE_USE_CASES = [
  "executeAppendProvenance",
  "executeAttachDocumentArtefact",
  "executeListDocumentArtefacts",
  "executeListProvenance"
] as const;
