/**
 * GetTrustFile DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTrustFileParams } from "@provenara/core/artworks";

export function createGetTrustFileRequest(overrides: Partial<GetTrustFileParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
