/**
 * Distribution Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/shares.openapi.types.js";
import { schemas } from "../schemas/shares.schemas.js";

/**
 * Entity: DistributionEntity
 * Description: Represents the Distribution domain model.
 * Source: schemas.Distribution
 * Type: Persisted Entity (x-dynamodb)
 */
export const DistributionEntitySchema = schemas.Distribution;
export type DistributionEntity = components["schemas"]["Distribution"];
