/**
 * Freeze Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/shares.openapi.types.js";
import { schemas } from "../schemas/shares.schemas.js";

/**
 * Entity: FreezeEntity
 * Description: Represents the Freeze domain model.
 * Source: schemas.ShareClass
 * Type: Persisted Entity (x-dynamodb)
 */
export const FreezeEntitySchema = schemas.ShareClass;
export type FreezeEntity = components["schemas"]["ShareClass"];
