/**
 * Subscription Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/shares.openapi.types.js";
import { schemas } from "../schemas/shares.schemas.js";

/**
 * Entity: SubscriptionEntity
 * Description: Represents the Subscription domain model.
 * Source: schemas.InvestorPosition
 * Type: Persisted Entity (x-dynamodb)
 */
export const SubscriptionEntitySchema = schemas.InvestorPosition;
export type SubscriptionEntity = components["schemas"]["InvestorPosition"];
