/**
 * Transfer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/shares.openapi.types.js";
import { schemas } from "../schemas/shares.schemas.js";

/**
 * Entity: TransferEntity
 * Description: Represents the Transfer domain model.
 * Source: schemas.Transfer
 * Type: Persisted Entity (x-dynamodb)
 */
export const TransferEntitySchema = schemas.Transfer;
export type TransferEntity = components["schemas"]["Transfer"];
