/**
 * Mismatch Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MismatchEntity } from "@provenara/core/custody/models/index.js";
import { custodySchemas } from "@provenara/core/custody";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cus";

export function createMismatch(overrides: Partial<MismatchEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cus_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artworkId: overrides.artworkId ?? faker.string.uuid(),
    eventType: overrides.eventType ?? "intake",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return custodySchemas.CustodyEvent.parse(raw);
}

export function mismatchBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMismatch(overrides));
}
