/**
 * ExecuteListArtworks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListArtworks Use Case
 *
 * DDD: Application use case for list Artwork.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListArtworksInput, ListArtworksOutput } from "../dto/artwork.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ArtworkRepository } from "../ports";

export class ExecuteListArtworks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly artwork: ArtworkRepository
  ) {}

  async execute(input: ListArtworksInput): Promise<ListArtworksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.artId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.artwork.listArtworks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListArtworksOutput;
  }
}
