/**
 * ExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExportRepository,
} from "@provenara/services/audits";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExportRepositoryDdb } from "./export-repository.ddb.js";

/**
 * ExportRepositoryAdapter
 *
 * Implements ExportRepository port for infrastructure layer.
 */
export class ExportRepositoryAdapter implements ExportRepository {
  private readonly ddb: ExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExportRepositoryDdb(this.dynamoClient);
  }

  async createProvenaraAuditExport(input: Parameters<ExportRepository['createProvenaraAuditExport']>[0]): Promise<Awaited<ReturnType<ExportRepository['createProvenaraAuditExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createProvenaraAuditExport(input);
  }

  async getAuditExport(input: Parameters<ExportRepository['getAuditExport']>[0]): Promise<Awaited<ReturnType<ExportRepository['getAuditExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAuditExport(input);
  }
}
