/**
 * FlagCustodyMismatch handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { flagCustodyMismatch } from "@provenara/api-server/domains/custody/handlers";
import type { CustodyDDDDependencies } from "@provenara/api-server/domains/custody";
import { createMismatch as createMismatchEntity } from "@provenara/factories/custody";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { CUSTODY_USE_CASES } from "../__factories__/use-cases.js";

describe("FlagCustodyMismatch", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CustodyDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CustodyDDDDependencies>(
      CUSTODY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createMismatchEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeFlagCustodyMismatch, "execute").mockResolvedValue(useCaseResult);

    await flagCustodyMismatch(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeFlagCustodyMismatch.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
