/**
 * InsuranceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InsuranceRepository Port
 *
 * DDD: Application port for insurancerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { BindInsurancePolicyInput, BindInsurancePolicyOutput, ListInsurancePoliciesInput, ListInsurancePoliciesOutput } from "../dto/insurance.dto";
export interface InsuranceRepository {
  listInsurancePolicies(input: ListInsurancePoliciesInput): Promise<ListInsurancePoliciesOutput>;
  bindInsurancePolicy(input: BindInsurancePolicyInput): Promise<BindInsurancePolicyOutput>;
}

export type { BindInsurancePolicyInput, BindInsurancePolicyOutput, ListInsurancePoliciesInput, ListInsurancePoliciesOutput } from "../dto/insurance.dto";
