/**
 * LapseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LapseRepository Port
 *
 * DDD: Application port for lapserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { LapseInsurancePolicyInput, LapseInsurancePolicyOutput } from "../dto/lapse.dto";
export interface LapseRepository {
  lapseInsurancePolicy(input: LapseInsurancePolicyInput): Promise<LapseInsurancePolicyOutput>;
}

export type { LapseInsurancePolicyInput, LapseInsurancePolicyOutput } from "../dto/lapse.dto";
