/**
 * CustodyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CustodyRepository Port
 *
 * DDD: Application port for custodyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttestCustodyInput, AttestCustodyOutput, ListCustodyEventsInput, ListCustodyEventsOutput } from "../dto/custody.dto";
export interface CustodyRepository {
  listCustodyEvents(input: ListCustodyEventsInput): Promise<ListCustodyEventsOutput>;
  attestCustody(input: AttestCustodyInput): Promise<AttestCustodyOutput>;
}

export type { AttestCustodyInput, AttestCustodyOutput, ListCustodyEventsInput, ListCustodyEventsOutput } from "../dto/custody.dto";
