/**
 * MismatchRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MismatchRepository Port
 *
 * DDD: Application port for mismatchrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClearCustodyMismatchInput, ClearCustodyMismatchOutput, FlagCustodyMismatchInput, FlagCustodyMismatchOutput } from "../dto/mismatch.dto";
export interface MismatchRepository {
  flagCustodyMismatch(input: FlagCustodyMismatchInput): Promise<FlagCustodyMismatchOutput>;
  clearCustodyMismatch(input: ClearCustodyMismatchInput): Promise<ClearCustodyMismatchOutput>;
}

export type { ClearCustodyMismatchInput, ClearCustodyMismatchOutput, FlagCustodyMismatchInput, FlagCustodyMismatchOutput } from "../dto/mismatch.dto";
