/**
 * ListAnchors handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAnchors } from "@provenara/api-server/domains/audits/handlers";
import type { AuditsDDDDependencies } from "@provenara/api-server/domains/audits";
import { createAnchor as createAnchorEntity } from "@provenara/factories/audits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { AUDITS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAnchors", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditsDDDDependencies>(
      AUDITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAnchorEntity({ orgId }),
      createAnchorEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAnchors, "execute").mockResolvedValue(useCaseResult);

    await listAnchors(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAnchors.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
