/**
 * ArtworkRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArtworkRepository Port
 *
 * DDD: Application port for artworkrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateArtworkInput, CreateArtworkOutput, GetArtworkInput, GetArtworkOutput, ListArtworksInput, ListArtworksOutput } from "../dto/artwork.dto";
export interface ArtworkRepository {
  listArtworks(input: ListArtworksInput): Promise<ListArtworksOutput>;
  createArtwork(input: CreateArtworkInput): Promise<CreateArtworkOutput>;
  getArtwork(input: GetArtworkInput): Promise<GetArtworkOutput>;
}

export type { CreateArtworkInput, CreateArtworkOutput, GetArtworkInput, GetArtworkOutput, ListArtworksInput, ListArtworksOutput } from "../dto/artwork.dto";
