/**
 * ExecuteClearCustodyMismatch - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteClearCustodyMismatch Use Case
 *
 * DDD: Application use case for get Mismatch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ClearCustodyMismatchInput, ClearCustodyMismatchOutput } from "../dto/mismatch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { MismatchRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteClearCustodyMismatch {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly mismatch: MismatchRepository
  ) {}

  async execute(input: ClearCustodyMismatchInput): Promise<ClearCustodyMismatchOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cusId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artworkId) {
      throw new ValidationError("artworkId is required");
    }
    const artworkId = (input as any).artworkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.mismatch.clearCustodyMismatch({ artworkId: artworkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artworkId}`);
    }

    return entity as ClearCustodyMismatchOutput;
  }
}
