/**
 * Shares DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Shares Domain Module - Composition root
 *
 * DDD: Composition root for shares domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DistributionRepositoryAdapter,
  FreezeRepositoryAdapter,
  ShareClassRepositoryAdapter,
  SubscriptionRepositoryAdapter,
  TransferRepositoryAdapter,
} from "@provenara/adapters/shares";
import { getIdGeneratorService } from "@provenara/adapters";
import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateShareClass,
  ExecuteFreezeShareClass,
  ExecuteGetShareClass,
  ExecuteListDistributions,
  ExecuteListInvestorPositions,
  ExecuteListShareClasses,
  ExecuteRecordDistribution,
  ExecuteSubscribeShares,
  ExecuteTransferShares,
} from "@provenara/services/shares/usecases";
// Ports (interfaces)
import type {
  DistributionRepository,
  FreezeRepository,
  ShareClassRepository,
  SubscriptionRepository,
  TransferRepository,
} from "@provenara/services/shares/ports";

export interface SharesDomainModule {
  repos: {
    distributions: DistributionRepository;
    freezes: FreezeRepository;
    shareClasses: ShareClassRepository;
    subscriptions: SubscriptionRepository;
    transfers: TransferRepository;
  };
  useCases: {
    distributions: {
      get: ExecuteRecordDistribution;
      list: ExecuteListDistributions;
    };
    freezes: {
      get: ExecuteFreezeShareClass;
    };
    shareClasses: {
      create: ExecuteCreateShareClass;
      get: ExecuteGetShareClass;
      list: ExecuteListShareClasses;
    };
    subscriptions: {
      get: ExecuteSubscribeShares;
      list: ExecuteListInvestorPositions;
    };
    transfers: {
      get: ExecuteTransferShares;
    };
  };
}

export function buildSharesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SharesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      distributions?: DistributionRepository;
      freezes?: FreezeRepository;
      shareClasses?: ShareClassRepository;
      subscriptions?: SubscriptionRepository;
      transfers?: TransferRepository;
    } = {};

    obj.distributions = new DistributionRepositoryAdapter(dynamoClient);
    obj.freezes = new FreezeRepositoryAdapter(dynamoClient);
    obj.shareClasses = new ShareClassRepositoryAdapter(dynamoClient);
    obj.subscriptions = new SubscriptionRepositoryAdapter(dynamoClient);
    obj.transfers = new TransferRepositoryAdapter(dynamoClient);
    return {
      distributions: obj.distributions!,
      freezes: obj.freezes!,
      shareClasses: obj.shareClasses!,
      subscriptions: obj.subscriptions!,
      transfers: obj.transfers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    distributions: {
      get: new ExecuteRecordDistribution(executionContext, idGenerator, repos.distributions),
      list: new ExecuteListDistributions(executionContext, idGenerator, repos.distributions),
    },
    freezes: {
      get: new ExecuteFreezeShareClass(executionContext, idGenerator, repos.freezes),
    },
    shareClasses: {
      create: new ExecuteCreateShareClass(executionContext, idGenerator, repos.shareClasses),
      get: new ExecuteGetShareClass(executionContext, idGenerator, repos.shareClasses),
      list: new ExecuteListShareClasses(executionContext, idGenerator, repos.shareClasses),
    },
    subscriptions: {
      get: new ExecuteSubscribeShares(executionContext, idGenerator, repos.subscriptions),
      list: new ExecuteListInvestorPositions(executionContext, idGenerator, repos.subscriptions),
    },
    transfers: {
      get: new ExecuteTransferShares(executionContext, idGenerator, repos.transfers),
    },
  };
  return { repos, useCases: useCases as SharesDomainModule["useCases"] };
}
