/**
 * DistributionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DistributionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DistributionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DistributionRepository,
} from "@provenara/services/shares";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DistributionRepositoryDdb } from "./distribution-repository.ddb.js";

/**
 * DistributionRepositoryAdapter
 *
 * Implements DistributionRepository port for infrastructure layer.
 */
export class DistributionRepositoryAdapter implements DistributionRepository {
  private readonly ddb: DistributionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DistributionRepositoryDdb(this.dynamoClient);
  }

  async listDistributions(input: Parameters<DistributionRepository['listDistributions']>[0]): Promise<Awaited<ReturnType<DistributionRepository['listDistributions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDistributions(input);
  }

  async recordDistribution(input: Parameters<DistributionRepository['recordDistribution']>[0]): Promise<Awaited<ReturnType<DistributionRepository['recordDistribution']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordDistribution(input);
  }
}
