/**
 * Routes for Assign
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { assignRiskAlert } from "../handlers/assign.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function assignRoutes(fastify: FastifyInstance) {
  // POST /v1/alerts/{alertId}/assign (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/alerts/:alertId/assign",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlertsDependenciesForRequest();
        await assignRiskAlert(request, reply, deps);
      });
    }
  );


}
