/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { alertRoutes } from "./alert.routes.js";
export { assignRoutes } from "./assign.routes.js";
export { resolveRoutes } from "./resolve.routes.js";
