/**
 * Repository interface for Insurance
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  InsuranceEntity
} from "../models/insurance.entity.js";
import type {
  ListInsurancePoliciesParams,
  InsurancePolicy
} from "../types/index.js";
/**
 * InsuranceRepository Interface
 */
export interface InsuranceRepository extends CreateReadRepository<InsuranceEntity, InsurancePolicy, string, ListInsurancePoliciesParams> {

}
