/**
 * CreateExpire DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ExpireValuationParams } from "@provenara/core/valuations";

export function createCreateExpireRequest(overrides: Partial<ExpireValuationParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
