/**
 * Routes for Anchor
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listAnchors, publishAnchor } from "../handlers/anchor.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function anchorRoutes(fastify: FastifyInstance) {
  // GET /v1/artworks/{artworkId}/anchors (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/artworks/:artworkId/anchors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await listAnchors(request, reply, deps);
      });
    }
  );


  // POST /v1/artworks/{artworkId}/anchors (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/artworks/:artworkId/anchors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { artworkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await publishAnchor(request, reply, deps);
      });
    }
  );


}
