/**
 * Custody DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custody
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Custody DTOs
 *
 * DDD: Application DTOs for Custody use cases.
 */

import type { AttestCustodyParams, AttestCustodyRequestInput, ListCustodyEventsParams } from "@provenara/core/custody/types";

export type ListCustodyEventsInput = ListCustodyEventsParams;

export type AttestCustodyInput = AttestCustodyParams & AttestCustodyRequestInput;

export type ListCustodyEventsOutput = {};

export type AttestCustodyOutput = {};
