/**
 * Alert Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/alerts.openapi.types.js";
import { schemas } from "../schemas/alerts.schemas.js";

/**
 * Entity: AlertEntity
 * Description: Represents the Alert domain model.
 * Source: schemas.RiskAlert
 * Type: Persisted Entity (x-dynamodb)
 */
export const AlertEntitySchema = schemas.RiskAlert;
export type AlertEntity = components["schemas"]["RiskAlert"];
