/**
 * GetCounterparty handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCounterparty } from "@provenara/api-server/domains/counterparties/handlers";
import type { CounterpartiesDDDDependencies } from "@provenara/api-server/domains/counterparties";
import { createCounterparty as createCounterpartyEntity } from "@provenara/factories/counterparties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@provenara/tests/shared";
import { COUNTERPARTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCounterparty", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CounterpartiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CounterpartiesDDDDependencies>(
      COUNTERPARTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createCounterpartyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCounterparty, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { counterpartyId: entity.id };

    await getCounterparty(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCounterparty.execute).toHaveBeenCalledWith(expect.objectContaining({ counterpartyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { counterpartyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCounterparty, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCounterparty(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
