/**
 * AnchorPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnchorPublisher Port
 *
 * DDD: Application port for anchorpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishAnchorInput, PublishAnchorOutput } from "../dto/anchor.dto";
export interface AnchorPublisher {
  publishAnchor(input: PublishAnchorInput): Promise<PublishAnchorOutput>;
}

export type { PublishAnchorInput, PublishAnchorOutput } from "../dto/anchor.dto";
