/**
 * ExecuteCreateProvenaraAuditExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateProvenaraAuditExport Use Case
 *
 * DDD: Application use case for create Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateProvenaraAuditExportInput, CreateProvenaraAuditExportOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ExportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateProvenaraAuditExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: CreateProvenaraAuditExportInput): Promise<CreateProvenaraAuditExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: artworkId, periodFrom, periodTo
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.periodTo) {
      throw new ValidationError("periodTo is required");
    }
    if (!input.periodFrom) {
      throw new ValidationError("periodFrom is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (audits domain)
    const entityId = this.idGenerator.audId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.exportRepo.createProvenaraAuditExport({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateProvenaraAuditExportOutput;
  }
}
