/**
 * Repository interface for Artwork
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ArtworkEntity
} from "../models/artwork.entity.js";
import type {
  ListArtworksParams,
  Artwork
} from "../types/index.js";
/**
 * ArtworkRepository Interface
 */
export interface ArtworkRepository extends CreateReadRepository<ArtworkEntity, Artwork, string, ListArtworksParams> {

}
