/**
 * Repository interface for TrustFile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TrustFileEntity
} from "../models/trust-file.entity.js";
/**
 * TrustFileRepository Interface
 */
export interface TrustFileRepository extends ReadRepository<TrustFileEntity, string, Record<string, never>> {

}
