/**
 * Repository interface for Encumbrance
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EncumbranceEntity
} from "../models/encumbrance.entity.js";
import type {
  ListEncumbrancesParams,
  Encumbrance
} from "../types/index.js";
/**
 * EncumbranceRepository Interface
 */
export interface EncumbranceRepository extends CreateReadRepository<EncumbranceEntity, Encumbrance, string, ListEncumbrancesParams> {

}
