/**
 * Repository interface for Title
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TitleEntity
} from "../models/title.entity.js";
import type {
  UpsertTitleStatusRequestInput
} from "../types/index.js";
/**
 * TitleRepository Interface
 */
export interface TitleRepository extends UpdateReadRepository<TitleEntity, UpsertTitleStatusRequestInput, string, Record<string, never>> {

}
