/**
 * Routes for Distribution
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listDistributions, recordDistribution } from "../handlers/distribution.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function distributionRoutes(fastify: FastifyInstance) {
  // GET /v1/share-classes/{shareClassId}/distributions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/share-classes/:shareClassId/distributions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { shareClassId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSharesDependenciesForRequest();
        await listDistributions(request, reply, deps);
      });
    }
  );


  // POST /v1/share-classes/{shareClassId}/distributions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/share-classes/:shareClassId/distributions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { shareClassId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSharesDependenciesForRequest();
        await recordDistribution(request, reply, deps);
      });
    }
  );


}
