/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { distributionRoutes } from "./distribution.routes.js";
export { freezeRoutes } from "./freeze.routes.js";
export { shareClassRoutes } from "./share-class.routes.js";
export { subscriptionRoutes } from "./subscription.routes.js";
export { transferRoutes } from "./transfer.routes.js";
