/**
 * Repository interface for Document
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DocumentEntity
} from "../models/document.entity.js";
import type {
  ListDocumentArtefactsParams,
  DocumentArtefact
} from "../types/index.js";
/**
 * DocumentRepository Interface
 */
export interface DocumentRepository extends CreateReadRepository<DocumentEntity, DocumentArtefact, string, ListDocumentArtefactsParams> {

}
