/**
 * Repository interface for Provenance
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProvenanceEntity
} from "../models/provenance.entity.js";
import type {
  ListProvenanceParams,
  ProvenanceEvent
} from "../types/index.js";
/**
 * ProvenanceRepository Interface
 */
export interface ProvenanceRepository extends CreateReadRepository<ProvenanceEntity, ProvenanceEvent, string, ListProvenanceParams> {

}
