/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: artworks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./artwork-repository.ddb.js";
export * from "./trust-file-repository.ddb.js";
export * from "./artwork-repository.adapter.js";
export * from "./trust-file-repository.adapter.js";
