/**
 * Title DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Title Domain Module - Composition root
 *
 * DDD: Composition root for title domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EncumbranceRepositoryAdapter,
  ReleaseRepositoryAdapter,
  TitleRepositoryAdapter,
} from "@provenara/adapters/title";
import { getIdGeneratorService } from "@provenara/adapters";
import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetTitleStatus,
  ExecuteListEncumbrances,
  ExecuteRecordEncumbrance,
  ExecuteReleaseEncumbrance,
  ExecuteUpsertTitleStatus,
} from "@provenara/services/title/usecases";
// Ports (interfaces)
import type {
  EncumbranceRepository,
  ReleaseRepository,
  TitleRepository,
} from "@provenara/services/title/ports";

export interface TitleDomainModule {
  repos: {
    encumbrances: EncumbranceRepository;
    releases: ReleaseRepository;
    titles: TitleRepository;
  };
  useCases: {
    encumbrances: {
      get: ExecuteRecordEncumbrance;
      list: ExecuteListEncumbrances;
    };
    releases: {
      get: ExecuteReleaseEncumbrance;
    };
    titles: {
      get: ExecuteUpsertTitleStatus;
    };
  };
}

export function buildTitleDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TitleDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      encumbrances?: EncumbranceRepository;
      releases?: ReleaseRepository;
      titles?: TitleRepository;
    } = {};

    obj.encumbrances = new EncumbranceRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    obj.titles = new TitleRepositoryAdapter(dynamoClient);
    return {
      encumbrances: obj.encumbrances!,
      releases: obj.releases!,
      titles: obj.titles!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    encumbrances: {
      get: new ExecuteRecordEncumbrance(executionContext, idGenerator, repos.encumbrances),
      list: new ExecuteListEncumbrances(executionContext, idGenerator, repos.encumbrances),
    },
    releases: {
      get: new ExecuteReleaseEncumbrance(executionContext, idGenerator, repos.releases),
    },
    titles: {
      get: new ExecuteUpsertTitleStatus(executionContext, idGenerator, repos.titles),
    },
  };
  return { repos, useCases: useCases as TitleDomainModule["useCases"] };
}
