/**
 * ShareClass Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ShareClassEntity } from "@provenara/core/shares/models/index.js";
import { sharesSchemas } from "@provenara/core/shares";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "shr";

export function createShareClass(overrides: Partial<ShareClassEntity> = {}) {
  const raw = {
    id: overrides.id ?? `shr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artworkId: overrides.artworkId ?? faker.string.uuid(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    totalShares: overrides.totalShares ?? faker.number.int(),
    ...overrides,
  };

  return sharesSchemas.ShareClass.parse(raw);
}

export function shareClassBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createShareClass(overrides));
}
