/**
 * Counterparties DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Counterparties Domain Module - Composition root
 *
 * DDD: Composition root for counterparties domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CounterpartyRepositoryAdapter,
  OverrideRepositoryAdapter,
  ScreenRepositoryAdapter,
} from "@provenara/adapters/counterparties";
import { getIdGeneratorService } from "@provenara/adapters";
import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCounterparty,
  ExecuteGetCounterparty,
  ExecuteListCounterparties,
  ExecuteOverrideScreenResult,
  ExecuteScreenCounterparty,
} from "@provenara/services/counterparties/usecases";
// Ports (interfaces)
import type {
  CounterpartyRepository,
  OverrideRepository,
  ScreenRepository,
} from "@provenara/services/counterparties/ports";

export interface CounterpartiesDomainModule {
  repos: {
    counterparties: CounterpartyRepository;
    overrides: OverrideRepository;
    screens: ScreenRepository;
  };
  useCases: {
    counterparties: {
      create: ExecuteCreateCounterparty;
      get: ExecuteGetCounterparty;
      list: ExecuteListCounterparties;
    };
    overrides: {
      get: ExecuteOverrideScreenResult;
    };
    screens: {
      get: ExecuteScreenCounterparty;
    };
  };
}

export function buildCounterpartiesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CounterpartiesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      counterparties?: CounterpartyRepository;
      overrides?: OverrideRepository;
      screens?: ScreenRepository;
    } = {};

    obj.counterparties = new CounterpartyRepositoryAdapter(dynamoClient);
    obj.overrides = new OverrideRepositoryAdapter(dynamoClient);
    obj.screens = new ScreenRepositoryAdapter(dynamoClient);
    return {
      counterparties: obj.counterparties!,
      overrides: obj.overrides!,
      screens: obj.screens!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    counterparties: {
      create: new ExecuteCreateCounterparty(executionContext, idGenerator, repos.counterparties),
      get: new ExecuteGetCounterparty(executionContext, idGenerator, repos.counterparties),
      list: new ExecuteListCounterparties(executionContext, idGenerator, repos.counterparties),
    },
    overrides: {
      get: new ExecuteOverrideScreenResult(executionContext, idGenerator, repos.overrides),
    },
    screens: {
      get: new ExecuteScreenCounterparty(executionContext, idGenerator, repos.screens),
    },
  };
  return { repos, useCases: useCases as CounterpartiesDomainModule["useCases"] };
}
