/**
 * ExecuteListValuations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListValuations Use Case
 *
 * DDD: Application use case for list Valuation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListValuationsInput, ListValuationsOutput } from "../dto/valuation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ValuationRepository } from "../ports";

export class ExecuteListValuations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly valuation: ValuationRepository
  ) {}

  async execute(input: ListValuationsInput): Promise<ListValuationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.valuation.listValuations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListValuationsOutput;
  }
}
