/**
 * ExecuteAddValuation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAddValuation Use Case
 *
 * DDD: Application use case for create Valuation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AddValuationInput, AddValuationOutput } from "../dto/valuation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ValuationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteAddValuation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly valuation: ValuationRepository
  ) {}

  async execute(input: AddValuationInput): Promise<AddValuationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: amount, currency, expiresOn, method, valuedOn, valuer
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.amount) {
      throw new ValidationError("amount is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }
    if (!input.valuer) {
      throw new ValidationError("valuer is required");
    }
    if (!input.method) {
      throw new ValidationError("method is required");
    }
    if (!input.valuedOn) {
      throw new ValidationError("valuedOn is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (valuations domain)
    const entityId = this.idGenerator.valId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.valuation.addValuation({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as AddValuationOutput;
  }
}
