/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Insurance Domain Use Cases
 * 
 * List of all use case names for the insurance domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const INSURANCE_USE_CASES = [
  "executeBindInsurancePolicy",
  "executeLapseInsurancePolicy",
  "executeListInsurancePolicies"
] as const;
