/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Valuations Domain Use Cases
 * 
 * List of all use case names for the valuations domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VALUATIONS_USE_CASES = [
  "executeAddValuation",
  "executeExpireValuation",
  "executeListValuations"
] as const;
