/**
 * ExecuteRecordEncumbrance - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: title
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordEncumbrance Use Case
 *
 * DDD: Application use case for get Encumbrance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordEncumbranceInput, RecordEncumbranceOutput } from "../dto/encumbrance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { EncumbranceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordEncumbrance {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly encumbrance: EncumbranceRepository
  ) {}

  async execute(input: RecordEncumbranceInput): Promise<RecordEncumbranceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ttlId();

    // All field names extracted from OpenAPI spec: amount, collateralType, currency, holderRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artworkId) {
      throw new ValidationError("artworkId is required");
    }
    const artworkId = (input as any).artworkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.encumbrance.recordEncumbrance({ artworkId: artworkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artworkId}`);
    }

    return entity as RecordEncumbranceOutput;
  }
}
