/**
 * ExecuteBindInsurancePolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteBindInsurancePolicy Use Case
 *
 * DDD: Application use case for get Insurance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { BindInsurancePolicyInput, BindInsurancePolicyOutput } from "../dto/insurance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { InsuranceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteBindInsurancePolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly insurance: InsuranceRepository
  ) {}

  async execute(input: BindInsurancePolicyInput): Promise<BindInsurancePolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.insId();

    // All field names extracted from OpenAPI spec: coverageAmount, currency, effectiveOn, expiresOn, insurerRef, policyNumber
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artworkId) {
      throw new ValidationError("artworkId is required");
    }
    const artworkId = (input as any).artworkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.insurance.bindInsurancePolicy({ artworkId: artworkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artworkId}`);
    }

    return entity as BindInsurancePolicyOutput;
  }
}
