/**
 * Counterparties Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createCounterparty_Body = z
  .object({
    name: z.string(),
    role: z.enum(['seller', 'borrower', 'investor', 'custodian', 'insurer']),
  })
  .passthrough();
const overrideScreenResult_Body = z
  .object({ reason: z.string(), approverRef: z.string() })
  .passthrough();

export const schemas: any = {
  createCounterparty_Body,
  overrideScreenResult_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/counterparties',
    alias: 'listCounterparties',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'role',
        type: 'Query',
        schema: z
          .enum(['seller', 'borrower', 'investor', 'custodian', 'insurer'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
                  tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  role: z.enum([
                    'seller',
                    'borrower',
                    'investor',
                    'custodian',
                    'insurer',
                  ]),
                  lastScreenOutcome: z
                    .enum(['clear', 'hit', 'error', 'pending'])
                    .optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/counterparties',
    alias: 'createCounterparty',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createCounterparty_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            role: z.enum([
              'seller',
              'borrower',
              'investor',
              'custodian',
              'insurer',
            ]),
            lastScreenOutcome: z
              .enum(['clear', 'hit', 'error', 'pending'])
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v1/counterparties/:counterpartyId',
    alias: 'getCounterparty',
    requestFormat: 'json',
    parameters: [
      {
        name: 'counterpartyId',
        type: 'Path',
        schema: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            role: z.enum([
              'seller',
              'borrower',
              'investor',
              'custodian',
              'insurer',
            ]),
            lastScreenOutcome: z
              .enum(['clear', 'hit', 'error', 'pending'])
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/counterparties/:counterpartyId/screen',
    alias: 'screenCounterparty',
    requestFormat: 'json',
    parameters: [
      {
        name: 'counterpartyId',
        type: 'Path',
        schema: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^scr_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            counterpartyId: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
            outcome: z.enum(['clear', 'hit', 'error']),
            screenedAt: z.string().datetime({ offset: true }),
            overridden: z.boolean().optional(),
            overrideReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/counterparties/:counterpartyId/screen/override',
    alias: 'overrideScreenResult',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: overrideScreenResult_Body,
      },
      {
        name: 'counterpartyId',
        type: 'Path',
        schema: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^scr_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            counterpartyId: z.string().regex(/^ctp_[0-9A-HJKMNP-TV-Z]{26}$/),
            outcome: z.enum(['clear', 'hit', 'error']),
            screenedAt: z.string().datetime({ offset: true }),
            overridden: z.boolean().optional(),
            overrideReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
