/**
 * Valuations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: valuations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Valuations Domain Module - Composition root
 *
 * DDD: Composition root for valuations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExpireRepositoryAdapter,
  ValuationRepositoryAdapter,
} from "@provenara/adapters/valuations";
import { getIdGeneratorService } from "@provenara/adapters";
import type { AdapterDynamoDBClient } from "@provenara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAddValuation,
  ExecuteExpireValuation,
  ExecuteListValuations,
} from "@provenara/services/valuations/usecases";
// Ports (interfaces)
import type {
  ExpireRepository,
  ValuationRepository,
} from "@provenara/services/valuations/ports";

export interface ValuationsDomainModule {
  repos: {
    expires: ExpireRepository;
    valuations: ValuationRepository;
  };
  useCases: {
    expires: {
      get: ExecuteExpireValuation;
    };
    valuations: {
      create: ExecuteAddValuation;
      list: ExecuteListValuations;
    };
  };
}

export function buildValuationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ValuationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      expires?: ExpireRepository;
      valuations?: ValuationRepository;
    } = {};

    obj.expires = new ExpireRepositoryAdapter(dynamoClient);
    obj.valuations = new ValuationRepositoryAdapter(dynamoClient);
    return {
      expires: obj.expires!,
      valuations: obj.valuations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    expires: {
      get: new ExecuteExpireValuation(executionContext, idGenerator, repos.expires),
    },
    valuations: {
      create: new ExecuteAddValuation(executionContext, idGenerator, repos.valuations),
      list: new ExecuteListValuations(executionContext, idGenerator, repos.valuations),
    },
  };
  return { repos, useCases: useCases as ValuationsDomainModule["useCases"] };
}
