/**
 * ExecuteListDistributions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDistributions Use Case
 *
 * DDD: Application use case for list Distribution.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDistributionsInput, ListDistributionsOutput } from "../dto/distribution.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { DistributionRepository } from "../ports";

export class ExecuteListDistributions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly distribution: DistributionRepository
  ) {}

  async execute(input: ListDistributionsInput): Promise<ListDistributionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.distribution.listDistributions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDistributionsOutput;
  }
}
