/**
 * ExecuteTransferShares - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteTransferShares Use Case
 *
 * DDD: Application use case for get Transfer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { TransferSharesInput, TransferSharesOutput } from "../dto/transfer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { TransferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteTransferShares {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly transfer: TransferRepository
  ) {}

  async execute(input: TransferSharesInput): Promise<TransferSharesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: fromInvestorId, shares, toInvestorId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).shareClassId) {
      throw new ValidationError("shareClassId is required");
    }
    const shareclassId = (input as any).shareClassId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.transfer.transferShares({ shareClassId: shareclassId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${shareclassId}`);
    }

    return entity as TransferSharesOutput;
  }
}
