/**
 * ExecuteGetShareClass - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetShareClass Use Case
 *
 * DDD: Application use case for get ShareClass.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetShareClassInput, GetShareClassOutput } from "../dto/share-class.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ShareClassRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetShareClass {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly shareClass: ShareClassRepository
  ) {}

  async execute(input: GetShareClassInput): Promise<GetShareClassOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).shareClassId) {
      throw new ValidationError("shareClassId is required");
    }
    const shareclassId = (input as any).shareClassId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.shareClass.getShareClass({ shareClassId: shareclassId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${shareclassId}`);
    }

    return entity as GetShareClassOutput;
  }
}
