/**
 * ExecuteListShareClasses - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListShareClasses Use Case
 *
 * DDD: Application use case for list ShareClass.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListShareClassesInput, ListShareClassesOutput } from "../dto/share-class.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { ShareClassRepository } from "../ports";

export class ExecuteListShareClasses {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly shareClass: ShareClassRepository
  ) {}

  async execute(input: ListShareClassesInput): Promise<ListShareClassesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.shareClass.listShareClasses({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListShareClassesOutput;
  }
}
