/**
 * Insurance Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/insurance.openapi.types.js";
import { schemas } from "../schemas/insurance.schemas.js";

/**
 * Entity: InsuranceEntity
 * Description: Represents the Insurance domain model.
 * Source: schemas.InsurancePolicy
 * Type: Persisted Entity (x-dynamodb)
 */
export const InsuranceEntitySchema = schemas.InsurancePolicy;
export type InsuranceEntity = components["schemas"]["InsurancePolicy"];
