/**
 * Lapse Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: insurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/insurance.openapi.types.js";
import { schemas } from "../schemas/insurance.schemas.js";

/**
 * Entity: LapseEntity
 * Description: Represents the Lapse domain model.
 * Source: schemas.InsurancePolicy
 * Type: Persisted Entity (x-dynamodb)
 */
export const LapseEntitySchema = schemas.InsurancePolicy;
export type LapseEntity = components["schemas"]["InsurancePolicy"];
