/**
 * OverrideRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverrideRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OverrideRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OverrideRepository,
} from "@provenara/services/counterparties";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OverrideRepositoryDdb } from "./override-repository.ddb.js";

/**
 * OverrideRepositoryAdapter
 *
 * Implements OverrideRepository port for infrastructure layer.
 */
export class OverrideRepositoryAdapter implements OverrideRepository {
  private readonly ddb: OverrideRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OverrideRepositoryDdb(this.dynamoClient);
  }

  async overrideScreenResult(input: Parameters<OverrideRepository['overrideScreenResult']>[0]): Promise<Awaited<ReturnType<OverrideRepository['overrideScreenResult']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.overrideScreenResult(input);
  }
}
