/**
 * ExecuteCreateCounterparty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateCounterparty Use Case
 *
 * DDD: Application use case for create Counterparty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateCounterpartyInput, CreateCounterpartyOutput } from "../dto/counterparty.dto";
import type { ExecutionContextService, IdGeneratorService } from "@provenara/services/_shared/index.js";
import type { CounterpartyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateCounterparty {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly counterparty: CounterpartyRepository
  ) {}

  async execute(input: CreateCounterpartyInput): Promise<CreateCounterpartyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctpId();

    // All field names extracted from OpenAPI spec: name, role
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (counterparties domain)
    const entityId = this.idGenerator.ctpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.counterparty.createCounterparty({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateCounterpartyOutput;
  }
}
