/**
 * Override DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Override DTOs
 *
 * DDD: Application DTOs for Override use cases.
 */

import type { OverrideScreenResultParams, OverrideScreenResultRequestInput } from "@provenara/core/counterparties/types";

export type OverrideScreenResultInput = OverrideScreenResultParams & OverrideScreenResultRequestInput;

export type OverrideScreenResultOutput = {};
