/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { GetRiskAlertParams, ListRiskAlertsParams } from "@provenara/core/alerts/types";

export type ListRiskAlertsInput = ListRiskAlertsParams;

export type GetRiskAlertInput = GetRiskAlertParams;

export type ListRiskAlertsOutput = {};

export type GetRiskAlertOutput = {};
