/**
 * ScreenRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counterparties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScreenRepository Port
 *
 * DDD: Application port for screenrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ScreenCounterpartyInput, ScreenCounterpartyOutput } from "../dto/screen.dto";
export interface ScreenRepository {
  screenCounterparty(input: ScreenCounterpartyInput): Promise<ScreenCounterpartyOutput>;
}

export type { ScreenCounterpartyInput, ScreenCounterpartyOutput } from "../dto/screen.dto";
